FROM node:20-alpine
COPY package*.json ./
RUN npm install
ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
ENV NEW_RELIC_LOG=stdout
ENV NEW_RELIC_LICENSE_KEY=eu01xxaf1ba8ff0307d3eb74673a463eFFFFNRAL
ENV NEW_RELIC_APP_NAME="my-node-app"
COPY . .
EXPOSE 3000
CMD ["node", "index.js"]
